services:
  - type: web
    name: restha-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: OWNER_NUMBER
        value: "6281339467851"
      - key: OWNER_NAME
        value: "Putu Pasek Jade Aurestha"
      - key: GEMINI_API_KEY
        sync: false

